"use client";

import { useEffect, useState } from "react";
import { apiRequest, errorMessage } from "@/lib/api/client";
import type { AdminOrder, AdminPaginator } from "@/types/admin";
import { DetailLink, EmptyState, ErrorState, LoadingRows, PageTitle, Pagination, StatusBadge } from "@/components/admin/admin-ui";

export default function OrdersPage() {
  const [data, setData] = useState<AdminPaginator<AdminOrder>>(); const [filters, setFilters] = useState({ search: "", type: "", status: "", payment_status: "" }); const [page, setPage] = useState(1); const [error, setError] = useState("");
  useEffect(() => { const t = setTimeout(() => { const q = new URLSearchParams({ page: String(page) }); Object.entries(filters).forEach(([k, v]) => { if (v) q.set(k, v); }); apiRequest<AdminPaginator<AdminOrder>>(`/admin/orders?${q}`).then(setData).catch((e) => setError(errorMessage(e))); }, 250); return () => clearTimeout(t); }, [filters, page]);
  const field = (key: keyof typeof filters, value: string) => { setFilters((f) => ({ ...f, [key]: value })); setPage(1); };
  return <><PageTitle title="Orders" description="Monitoring read-only lifecycle Ride, Food, dan Send." /><div className="mb-5 grid gap-2 md:grid-cols-4"><input className="admin-input" placeholder="Nomor order" value={filters.search} onChange={(e) => field("search", e.target.value)} /><select className="admin-input" value={filters.type} onChange={(e) => field("type", e.target.value)}><option value="">Semua tipe</option>{["ride", "food", "send"].map((v) => <option key={v}>{v}</option>)}</select><input className="admin-input" placeholder="Status" value={filters.status} onChange={(e) => field("status", e.target.value)} /><select className="admin-input" value={filters.payment_status} onChange={(e) => field("payment_status", e.target.value)}><option value="">Semua pembayaran</option>{["pending", "paid", "failed", "refunded"].map((v) => <option key={v}>{v}</option>)}</select></div>{error ? <ErrorState message={error} /> : !data ? <LoadingRows /> : !data.data.length ? <EmptyState /> : <div className="admin-card overflow-x-auto"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Tipe</th><th>Status</th><th>Payment</th><th>Total</th><th>Dibuat</th><th></th></tr></thead><tbody>{data.data.map((o) => <tr key={o.id}><td className="font-bold">{o.order_number}</td><td>{o.customer?.name ?? o.user?.name ?? "-"}</td><td>{o.type}</td><td><StatusBadge value={o.status} /></td><td><StatusBadge value={o.payment_status} /></td><td>Rp {Number(o.total_price).toLocaleString("id-ID")}</td><td>{new Date(o.created_at).toLocaleDateString("id-ID")}</td><td><DetailLink href={`/orders/${o.id}`} /></td></tr>)}</tbody></table><Pagination page={data.current_page} lastPage={data.last_page} onPage={setPage} /></div>}</>;
}
