"use client";

import { use, useEffect, useState } from "react";
import { apiRequest, errorMessage } from "@/lib/api/client";
import type { AdminOrder } from "@/types/admin";
import { ErrorState, LoadingRows, PageTitle, StatusBadge } from "@/components/admin/admin-ui";

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="admin-card"><h2 className="mb-3 font-black">{title}</h2>{children}</section>; }
export default function OrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [order, setOrder] = useState<AdminOrder>(); const [error, setError] = useState(""); useEffect(() => { apiRequest<{ order: AdminOrder }>(`/admin/orders/${id}`).then((r) => setOrder(r.order)).catch((e) => setError(errorMessage(e))); }, [id]);
  return <><PageTitle title={order?.order_number ?? "Detail order"} description="Lifecycle order bersifat read-only untuk administrator." />{error ? <ErrorState message={error} /> : !order ? <LoadingRows /> : <div className="grid gap-5 lg:grid-cols-2"><Section title="Ringkasan"><div className="space-y-2 text-sm"><p>Tipe: <strong>{order.type}</strong></p><div className="flex gap-2"><StatusBadge value={order.status} /><StatusBadge value={order.payment_status} /></div><p>Customer: {order.user?.name ?? "-"}</p><p>Driver: {order.driver?.user?.name ?? "-"}</p><p>Merchant: {order.merchant?.name ?? "-"}</p><p>Dibuat: {new Date(order.created_at).toLocaleString("id-ID")}</p></div></Section><Section title="Rute"><p className="text-sm"><strong>Pickup</strong><br />{order.pickup_address}</p><p className="mt-4 text-sm"><strong>Tujuan</strong><br />{order.destination_address}</p><p className="mt-4 text-sm">Jarak: {order.distance ?? "-"} km</p></Section>{order.send_details ? <Section title="Detail kiriman"><pre className="whitespace-pre-wrap text-sm">{JSON.stringify(order.send_details, null, 2)}</pre></Section> : null}{order.items?.length ? <Section title="Items">{order.items.map((item) => <div key={item.id} className="mb-2 rounded-xl bg-slate-50 p-3 text-sm"><strong>{item.product_name}</strong><p>{item.quantity} × Rp {Number(item.price).toLocaleString("id-ID")}</p></div>)}</Section> : null}<Section title="Pricing"><dl className="space-y-2 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>Rp {Number(order.subtotal).toLocaleString("id-ID")}</dd></div><div className="flex justify-between"><dt>Delivery</dt><dd>Rp {Number(order.delivery_fee).toLocaleString("id-ID")}</dd></div><div className="flex justify-between"><dt>Service</dt><dd>Rp {Number(order.service_fee).toLocaleString("id-ID")}</dd></div><div className="flex justify-between border-t pt-2 font-black"><dt>Total</dt><dd>Rp {Number(order.total_price).toLocaleString("id-ID")}</dd></div></dl></Section><Section title="Payment & rating"><pre className="whitespace-pre-wrap text-sm">{JSON.stringify({ payment: order.payment, rating: order.rating }, null, 2)}</pre></Section><Section title="Status history"><div className="space-y-3">{order.status_histories?.map((h) => <div key={h.id} className="border-l-2 border-amber-400 pl-3 text-sm"><strong>{h.status.replaceAll("_", " ")}</strong><p className="text-slate-500">{h.note}</p><small>{new Date(h.created_at).toLocaleString("id-ID")}</small></div>)}</div></Section></div>}</>;
}
